# this compose file contains overrides for local development
services:
  klips-api:
    build: ./klips-api
    ports:
      - 3000:3000

  dispatcher:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/dispatcher/Dockerfile

  error-handler:
    build: ./worker/error-handler

  rollback-handler:
    build: ./worker/rollback-handler

  send-mattermost-message:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/send-mattermost-message/Dockerfile

  send-email:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/send-email/Dockerfile

  geoserver-publish-imagemosaic:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/geoserver-publish-imagemosaic/Dockerfile

  geoserver-create-and-apply-sld:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/geoserver-create-and-apply-sld/Dockerfile

  geoserver-create-imagemosaic-datastore:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/geoserver-create-imagemosaic-datastore/Dockerfile

  download-file:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/download-file/Dockerfile

  geotiff-optimizer:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/geotiff-optimizer/Dockerfile

  geotiff-validator:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/geotiff-validator/Dockerfile

  dataset-rotation:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/dataset-rotation/Dockerfile

  dataset-archive:
    build:
      context: ../rabbitmq-worker
      dockerfile: ../rabbitmq-worker/src/dataset-archive/Dockerfile

  geoserver:
    build: ./geoserver
    environment:
      - INSTALL_EXTENSIONS=true
      - STABLE_EXTENSIONS=importer
      - EXTRA_JAVA_OPTS=-Xms1g -Xmx8g
      - SKIP_DEMO_DATA=true
      - GEOSERVER_CSRF_DISABLED=true
    ports:
     - 8080:8080

  geoserver-init:
    build: ./geoserver-init

  pygeoapi:
    build: ./pygeoapi
    ports:
      - 127.0.0.1:5000:80

  klips-chart-api:
    build: ./easy-to-use-api/klips-chart-api
    ports:
      - 3001:80

  klips-timelapse-video-api:
    build: ./easy-to-use-api/klips-timelapse-video-api
    ports:
      - 3002:80

  klips-warning-api:
    build: ./easy-to-use-api/klips-warning-api
    ports:
      - 19007:80
  
  klips-url-generator:
    build: ./easy-to-use-api/klips-url-generator
    ports:
      - 3003:3000

  klips-wmts-slider:
    build: ./demonstrator-ogc-services/klips-wmts-slider
    ports:
      - 8081:80
  
  klips-wmts-demo:
    build: ./demonstrator-ogc-services/klips-wmts-demo
    ports:
      - 8082:80
  
  klips-wmts-demo-summer:
    build: ./demonstrator-ogc-services/klips-wmts-demo-summer
    ports:
      - 8084:80
      
  klips-wmts-simulation:
    build: ./demonstrator-ogc-services/klips-wmts-simulation
    ports:
      - 8083:80
  
  klips-dashboard:
    build: ./easy-to-use-api/klips-dashboard
    ports:
      - 3004:3000

  postgres:
    ports:
      - 5433:5432

  demonstrator:
    ports:
      - 8888:80

  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
